[project]
name = "demos"
version = "0.1.0"
description = "Global demographics data lakehouse on Databricks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyspark>=4.0.4",
]


[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
